### ISSUE TITLE
Transition matrix from `VBHMM.gen_M` is not row stochastic.

### ISSUE THREAD

**Issue by trivialfis** [austinjstromme/svihmm#2]
Maybe dividing a normalization term after generating transition matrix is needed?

**Comment by austinjstromme** [comment]
Hi Jiaming,

Sorry, I can't help you until the 22nd, am currently on vacation. Hopefully
it isn't too urgent. When I'm back I'll look into it.

Best,
Austin

**Comment by trivialfis** [comment]
@austinjstromme No problem.  I'm just reading your code for learning.  Thanks for the algorithm.
